parameters: {}
environment: {}
packages:
  - name: view
    environment:
      DATABASE_URL: "${DATABASE_URL}"

    parameters: {}
    functions:
    - name: refresh
      main: ''
      runtime: 'go:default'
      environment: {}
      parameters: {}
      triggers:
      - name: trigger-hello
        sourceType: scheduler
        sourceDetails:
          cron: "* * * * *"
          withBody:
            name: 'sammy'
